# Generated by Django 5.2.11 on 2026-02-16 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0002_prescription"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="prescription",
            new_name="medical_pre_patient_236837_idx",
            old_name="medical_pre_patient_idx",
        ),
        migrations.RenameIndex(
            model_name="prescription",
            new_name="medical_pre_medicat_c61deb_idx",
            old_name="medical_pre_medicat_idx",
        ),
        migrations.RenameIndex(
            model_name="prescription",
            new_name="medical_pre_status_096a4d_idx",
            old_name="medical_pre_status_idx",
        ),
    ]
