# Generated by Django 5.1.15 on 2026-02-17 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "medical",
            "0003_rename_medical_pre_patient_idx_medical_pre_patient_236837_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="medication",
            options={
                "ordering": ["code"],
                "verbose_name": "médicament",
                "verbose_name_plural": "médicaments",
            },
        ),
        migrations.AlterModelOptions(
            name="patient",
            options={
                "ordering": ["last_name", "first_name", "id"],
                "verbose_name": "patient",
                "verbose_name_plural": "patients",
            },
        ),
        migrations.AlterModelOptions(
            name="prescription",
            options={
                "ordering": ["-start_date", "id"],
                "verbose_name": "prescription",
                "verbose_name_plural": "prescriptions",
            },
        ),
    ]
